# Generated by Django 4.2.16 on 2024-10-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_image_doctor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
