# Generated by Django 4.2.16 on 2024-10-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
